### ISSUE TITLE
Change SE "Robot interference" tooltip to "Owlish interference"

### ISSUE THREAD

**Issue by Dodecaphone12** [cerulliulliulli/yeet-labels#1]
In the Universe Explorer of Earendel's Space Exploration mod, the column originally designated "Robot interference" successfully shows the owl replacement sprite for the logistic robot as an icon. Hovering over the icon shows the column name as a tooltip; for immersion, it would be good to see "Robot" replaced with "Owlish."

**Comment by cerulliulliulli** [comment]
Went with "Owl interference" for now. Would like to come up with some better names for these.
